<div class="pull-left">
    <a href="/" ><img src="" alt="cwtkd Logo" /> </a>
</div>
<div class="pull-right">
    Contact: 07525 028 166 -
    
    
    
    
    <span class="label">
        <i class="fa fa-facebook"></i>
    </span>
    <span class="label">
        <i class="fa fa-twitter"></i>
    </span>
    <span class="label">
        <i class="fa fa-envelope-o"></i>
    </span>
    
    <form class="form-inline">
        <input type="text" class="input-medium search-query">
        <button type="submit" class="btn">Search</button>
    </form>
</div>
