<div class="navbar navbar-inverse navbar-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>

            <div class=" nav-collapse collapse">
                <ul class="nav nav-pills">
                    <li><a href="/index"><i class="icon-dashboard"></i> Home</a></li>
                    <li><a href="/contact"><i class="icon-dashboard"></i> Contact</a></li>
                   
                </ul>
            </div>

               
            </div>
        </div>
    </div>