<h2 class="wsite-content-title" style="text-align:center;"><font size="7">Contact Form &amp; FAQ</font><br /><br /></h2>

<div class="row-fluid">
    <div class="span4">
        <h2 class="wsite-content-title" style="text-align:left;"><font size="4">Question:<br /><span></span></font> What do I need to start learning taekwondo?<br /></h2>
        <div class="paragraph" style="text-align:left;"><span></span><font size="3">Determination &amp; Patience and practice.</font><br /><font size="3">You will also require a Licence to begin training (this covers your insurance). Fitness will help but you will improve your fitness week on week.</font><br /></div>
        <h2 class="wsite-content-title" style="text-align:left;"><font size="4">Question:</font><br /><span>How much does a suit cost?</span><br /></h2>
        <span class='imgPusher' style='float:left;height:135px'></span><span style='z-index:10;position:relative;float:left;;clear:left;margin-top:20px;*margin-top:40px'><a><img src="/img/suit.jpg" style="margin-top: 5px; margin-bottom: 10px; margin-left: 0px; margin-right: 10px; border-width:0;" alt="Picture" class="galleryImageBorder wsite-image" /></a><span style="display: block; font-size: 90%; margin-top: -10px; margin-bottom: 10px; text-align: center;" class="wsite-caption"></span></span>
        <div class="paragraph" style="text-align:left;display:block;">Suits vary in price depending on the manufacturer &amp; quality. I sell suits within the club at &pound;25 for children up to 160cm to &pound;30 for Adults from 170cm +<br />If you are thinking of buying a suit online or locally please make sure it is a WTF style of suit with a white V-neck.&nbsp;A Taekwondo a suit is called a Dobok.</div>
    </div>
    <div class="span4">
        <h2 class="wsite-content-title" style="text-align:left;"><font size="4">Question:</font><br /><span></span> How much will it cost initially to start taekwondo?<br /></h2>
        <div class="paragraph" style="text-align:left;"><font size="3">To begin with all you need is a licence. This is purchased through your instructor &amp; covers you &amp; your instructors insurance to train. The cost is &pound;25 and needs renewing annually.<br /><span>You do not need to worry about purchasing a suit (Dobok) straight away, 4-6 weeks is a good time, this way you will know if you will enjoy learning Taekwondo.</span></font></div>
        <h2 class="wsite-content-title" style="text-align:left;"><font size="4">Question:</font><br /><span></span> How much does it cost per lesson?<br /></h2>
        <div class="paragraph" style="text-align:left;"><span></span><font size="3">Each session is &pound;5.00 or you can choose to pay a monthly fee of &pound;25.00 - this enables you to train for the whole month to any available lessons. *some special sessions/seminars are charged individually &amp; will be made clear prior to the event. The monthly fee can be paid on any date in the month &amp; can be standing order / cash or cheque.</font><br /></div>
    </div>
    <div class="span4">
        <h2 class="wsite-content-title" style="text-align:left;"><font size="4">Question:</font><br /><span></span> How old do I need to be to begin Taekwondo?<br /></h2>
        <div class="paragraph" style="text-align:left;"><font size="3">I start teaching from age 5 &amp;<br /><span></span>up - this is usually the time a child can concentrate for long enough to begin to really enjoy learning the Martial Art.</font><br /></div>
        <h2 class="wsite-content-title" style="text-align:left;"><font size="4">Question:</font><br />What do I need to wear to my first lesson?</h2>
        <div class="paragraph" style="text-align:left;"><font size="3">For your first lesson the best thing to do it wear Tracksuit style bottoms and a T-shirt. We train for Taekwondo in bare feet (unless you have a medical condition).</font><br /></div>
    </div>
</div>

<div>FORM HERE</div>
