<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('CWTKD - C W Taekwondo Milton Keynes');
echo $this->doctype(); ?>
<head>
    <?php echo $this->headMeta(); ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css')
                                 //->appendStylesheet($this->baseUrl().'/css/bootstrap-responsive.css')
                                 ->appendStylesheet($this->baseUrl().'//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css')
                                 ->appendStylesheet('//code.jquery.com/ui/1.10.3/themes/ui-darkness/jquery-ui.css')
                                 ->appendStylesheet('//fonts.googleapis.com/css?family=Dancing+Script:400,700')
                                 ->appendStylesheet('//fonts.googleapis.com/css?family=Telex')
                                 ->appendStylesheet('//fonts.googleapis.com/css?family=Lato:400,300,300italic,700,400italic,700italic')
                                 ->appendStylesheet('//fonts.googleapis.com/css?family=Questrial')
                                 ->appendStylesheet($this->baseUrl().'/css/site.css'); ?>
    <?php echo $this->headScript()->prependFile("//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js")
                                   ->appendFile("//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js")
                                   ->appendFile('//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js')
                                   ->appendFile($this->baseUrl().'/js/site.js'); ?>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

</head>
<body>

<div id="content">
    <div class="container-fluid">

        <div class="content">
            <header>
                <div class="row-fluid">
                    <?php echo $this->partial('partials/header.phtml'); ?>
                </div>
            </header>
                <?php echo $this->partial('partials/navigation.phtml'); ?>
            <article>
                <div class="row-fluid">
                    <div class="span2" id="left"><?php echo $this->partial('partials/left.phtml'); ?></div>
                    <div class="span8" id="main"><?php echo $this->layout()->content; ?></div>
                    <div class="span2" id="right"><?php echo $this->partial('partials/right.phtml'); ?></div>
                </div>
            </article>
            <footer>
                <?php echo $this->partial('partials/footer.phtml'); ?>
            </footer> <!-- /footer -->
        </div>

    </div> <!-- /container -->
</div>
</body>
</html>