<div class="navbar navbar-inverse navbar-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>

            <div class=" nav-collapse collapse">
                <ul class="nav nav-pills">
                    <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'index')); ?>"><i class="icon-dashboard"></i> Dashboard</a></li>
                   
                </ul>
            </div>

               
            </div>
        </div>
    </div>